default_platform(:ios)
ENV["TEAM_ID_ITC"] = "358421"

platform :ios do

  desc "Upload Production to TestFlight"
  lane :beta do

  	create_keychain(
        name: "actiontest_keychain",
        password: "meow",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )
    match(git_url: "https://nikunjagola1:b9b208e63775a774fffbe89788bd28d8a571dec7@github.com/nikunjagola1/nikunjCertificates.git",
          type: "appstore",
          keychain_name: "actiontest_keychain",
          keychain_password: "meow",
          username: "nikunj.agola@tatvasoft.com",
          app_identifier: "com.tatvasoft.vidoetest")
    # gym(scheme: "demoCI", export_method: "app-store", clean: true , disable_xcpretty: true)
    # upload_to_testflight(username: "nikunj.agola@tatvasoft.com", team_id: ENV["TEAM_ID_ITC"], skip_waiting_for_build_processing: true)
  end
end
