name: First App

on:
  issues:
    name: Monday
    types: [opened, edited, closed, milestoned]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo First App Script Run
