name: First App

on:
  milestone:
    name: Monday
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo First App Script Run
