name: Milestones

on:
  milestone:
    types: [created, opened, edited, closed, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      run: echo Hello, world!
