name: Job - Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: iOS develop
    runs-on: macOS-latest
    steps:
      - name: Force xcode 11
        run: |
          echo "Pushed to Develop"
          sudo xcode-select -switch /Applications/Xcode_11.1.app  

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: xoxp-426698273411-607720160771-860218110260-ccbc3fdb5d9117550ed88835e17c4074
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"DJ90G0D9V\",\"text\":\"Test Slack Bot Message\"}'
