name: Jon - Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: iOS develop
    runs-on: macOS-latest
    steps:
      - name: Force xcode 11
        run: |
          echo "Pushed to Develop"
          sudo xcode-select -switch /Applications/Xcode_11.1.app  

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
