name: Second App

on:
  milestone:
    name: Tuesday
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Second App Script Run
