name: Second App

on:
  issue_comment:
    types: [created, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Second App Script Run
